"""Create the email momodel

Revision ID: 45431ae01d81
Revises: f4bb3187fb6e
Create Date: 2020-09-29 20:23:08.279172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45431ae01d81'
down_revision = 'f4bb3187fb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_constraint('comments_name_key', 'comments', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('comments_name_key', 'comments', ['name'])
    op.drop_table('email')
    # ### end Alembic commands ###
