"""Create a comments model

Revision ID: f4bb3187fb6e
Revises: c459fab0e0b5
Create Date: 2020-09-28 23:33:01.370488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4bb3187fb6e'
down_revision = 'c459fab0e0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_posts_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.drop_column('comments', 'posts_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posts_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_posts_id_fkey', 'comments', 'posts', ['posts_id'], ['id'])
    op.drop_column('comments', 'post_id')
    # ### end Alembic commands ###
